### ISSUE TITLE
npm install: zsh: command not found: npm

### ISSUE THREAD

**Issue by ghost** [R-K-H/vogue-runway-scraper#10]
sorry im a complete noob, I downloaded the folder, opened it in terminal and typed nom install but I get the error
`zsh: command not found: npm
`

**Comment by ghost** [comment]
I guess I have no idea how to use this at all anyway

**Comment by R-K-H** [comment]
:)

That's ok, do you have node installed locally?

**Comment by ghost** [comment]
:(
I don't even know what node is.
don't worry, I made a keyboard maestro script to save the images for me!

**Comment by R-K-H** [comment]
Sorry. I added some more instructions. Glad your found a solution!
