### ISSUE TITLE
Cannot read property 'edges' of null

### ISSUE THREAD

**Issue by Whatsowhatso** [R-K-H/vogue-runway-scraper#8]
https://imgur.com/a/PYwoeEJ

started to get this error

tried on Spring 2016 Ready-to-Wear, Fall 2016 Ready-to-Wear, Resort 2017

in all three attempts it error-ed out on different designers after 200+ links

**Comment by R-K-H** [comment]
Ok, so I just checked this out and it works fine on my machine with what you posted in the example it looks like you were trying to scrape the `spring-2016-ready-to-wear` shows.

I'll adjust the code to check for nulls, but I'm not sure if it's not something related to rate limiting or something of that sort.

Let me push a fix really quick, although this will now use a .env file which you'll have to create from the example.env. Be sure to also do an `npm install` as I've also updated the packages.

**Comment by R-K-H** [comment]
Ok so.

Updated it to run off .env file, that's what will be used and updated the readme to reflect that. I also went ahead and added a rate limiting field so you can test that feature out and let me know if that fixes the issue, like before I think you were worried about hitting the servers too frequently.

I've also updated the display to reflect the correct value of size of the image, therefore you'll see KB / MB when downloading them to give you an idea of what kind of size it is.

As well updated for a check for null on the slidesV2, although I suspect it could be that they are just rate limiting your IP.

Let me know if you have any other questions. If not I'll close this out in a few days.

**Comment by Whatsowhatso** [comment]
Tried the older version the next day, it appears to be working as it should, probably jumped the gun on this "error". Any way thanks for the update.
